#!/usr/bin/env bash
# This displays a list of currently running processes
# Shows all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -a -x -u -f
